### ISSUE TITLE
column sensitivity issue

### ISSUE THREAD

**Issue by Melshaabiny** [Claviz/bellboy#40]
@jansivans It seems that the column names are being forced as case-sensitive. In my case, I am using MSSQLProcessor and PostgresDestination and was getting "XYZ" table or column does not exist on the pg side. When I used lowercase table name and edited PostgresDestination.prototype.loadBatch to convert "key" toLowerCase() that seemed to fix my issue, but I think this might be a broader bug so wanted to flag here. Could you please take pass at that?

**Comment by AlexTimo** [comment]
Hi Moustafa!

Can you post a snippet of your script? We use PostgresDestination a lot internally, so I'm curious what the issue might be.

Alex

**Comment by AlexTimo** [comment]
Hi @Melshaabiny ,

would you be able to provide a snippet of your code for us to investigate further?

**Comment by Melshaabiny** [comment]
@AlexTimo hey sorry for the delay on this. I revised the fix I described above to run this snippet in my code rather than edit the package
`                    recordGenerator: async function* (record) {
                      // Exclude the identity column, destination DB generates this
                      const  {ID, ...destinationRecord} = record
                      const newRecord = {}

                      Object.keys(destinationRecord).forEach(element => {
                        newRecord[element.toLowerCase()] = destinationRecord[element]
                      });
                      
                      yield newRecord;

                    }`
I guess the larger question is whether there can be a parameter in the origin and destination to specify the case-sensitivity preference.
