### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by teleological** [Claviz/bellboy#51]
I'm interested in contributing a PR to this project, but I see many test failures, even when running in Docker. Are the tests running for others?

**Comment by jansivans** [comment]
Hi.
Tests can be run by using `docker-compose up --abort-on-container-exit --exit-code-from test --build test` command.
I've set up GitHub [action](https://github.com/Claviz/bellboy/blob/master/.github/workflows/config.yml) to execute tests and it seems that all tests are passing [successfully](https://github.com/Claviz/bellboy/actions/runs/6081904038/job/16498556817).
What errors are you seeing?

**Comment by teleological** [comment]
Thank you so much for the reply. I know it can be thankless running an open source project. If I can use `bellboy` for my project, on the other hand, it will save me a lot of work. I chose `bellboy` over the other frameworks because it seems to be actively maintained and it is appreciably lightweight. So again, thank you for that.

I ran the command per your instructions, and well: Everything passed. Sorry for the false alarm. I wrongly assumed I could just run `docker-compose up`. I see that you documented this in the `README`. I owe you a PR and hope it is worth the trouble for you!

**Comment by AlexTimo** [comment]
@teleological,

if you need any help with setting up your bellboy jobs, just give me a shout.

Alex

**Comment by teleological** [comment]
Thank you, Alex! I submitted PR #52 which suggests a way to break dependencies on the `msnodesqlv8` package for users who don't need a native MSSQL driver. Would be very glad to have your feedback and to work with you on any changes that you would require in order to integrate it.
